src/AppBundle/Entity/Exencion.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\ManyToMany;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Exencion
 *
 * @ORM\Table(name="exencion")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ExencionRepository")
 */
class Exencion
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(name="Nombre", type="string", length=50)
     */
    private $nombre;

    /**
     * @var string
     * @ORM\Column(name="Codigo", type="string", length=9)
     */
    private $codigo;

    /**
     * @var int
     * @Assert\Type(type="int")
     * @Assert\GreaterThan(value="0")
     * @ORM\Column(name="HorasSemanales", type="integer")
     */
    private $HorasSemanales;

    /**
     * @var int
     * @Assert\Type(type="int")
     * @Assert\GreaterThan(value="0")
     * @ORM\Column(name="HorasTotales", type="integer")
     */
    private $HorasTotales;

    /**
     * @ManyToMany(targetEntity="Usuario", mappedBy="exencion",fetch="EXTRA_LAZY")
     * @ORM\JoinTable(name="usuario_extra_horas")
     * @var Collection
     */
    private $usuarios;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     * @return Exencion
     */
    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return string
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * @param string $nombre
     * @return Exencion
     */
    public function setNombre($nombre)
    {
        $this->nombre = ucfirst($nombre);
        return $this;
    }

    /**
     * @return string
     */
    public function getCodigo()
    {
        return $this->codigo;
    }

    /**
     * @param string $codigo
     * @return Exencion
     */
    public function setCodigo($codigo)
    {
        $this->codigo = $codigo;
        return $this;
    }

    /**
     * @return int
     */
    public function getHorasSemanales()
    {
        return $this->HorasSemanales;
    }

    /**
     * @param int $HorasSemanales
     * @return Exencion
     */
    public function setHorasSemanales($HorasSemanales)
    {
        $this->HorasSemanales = $HorasSemanales;
        return $this;
    }

    /**
     * @return int
     */
    public function getHorasTotales()
    {
        return $this->HorasTotales;
    }

    /**
     * @param int $HorasTotales
     * @return Exencion
     */
    public function setHorasTotales($HorasTotales)
    {
        $this->HorasTotales = $HorasTotales;
        return $this;
    }

    /**
     * @return Collection
     */
    public function getUsuarios()
    {
        return $this->usuarios;
    }

    /**
     * @param Usuario $usuarios
     * @return Exencion
     */
    public function addUsuarios(Usuario $usuarios)
    {
        if (false === $this->usuarios->contains($usuarios)) {
            $this->usuarios[] = $usuarios;
            $usuarios->addExencion($this);
        }

        return $this;
    }

    public function removeUsuarios(Usuario $usuario)
    {
        if (true === $this->usuarios->contains($usuario)) {
            $this->usuarios->removeElement($usuario);
            $usuario->removeExencion($this);
        }

    }

    public function __construct()
    {
        $this->usuarios = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getNombre();
    }

}

src/AppBundle/Controller/UsersController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Usuario;
use AppBundle\Form\Model\ChangePassword;
use AppBundle\Form\Type\ChangePasswordType;
use AppBundle\Form\Type\EditUserType;
use AppBundle\Form\Type\NewUserType;
use Doctrine\Common\Collections\ArrayCollection;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class UsersController extends Controller
{

    /**
     * @Route("/usuarios/", name = "listUsers")
     * @Security("has_role('ROLE_USER')")
     */
    public function indexUsuariosAction()
    {
        $usuarios = $this->getDoctrine()->getRepository(Usuario::class)->encontrarTodosUsuarios($this->getUser());
        $porcentajesMaterias = new ArrayCollection();
        $porcentajesExenciones = new ArrayCollection();

        foreach ($usuarios as $u) {
            $porcentajesMaterias [] = $this->getDoctrine()->getRepository(Usuario::class)->getPorcentajeMateriasAsignadas($u);
            $porcentajesExenciones [] = $this->getDoctrine()->getRepository(Usuario::class)->getPorcentajeExencionesAsignadas($u);

        }
        return $this->render('@App/users/index.html.twig', [
            'usuarios' => $usuarios,
            'porcentajesMaterias' => $porcentajesMaterias,
            'porcentajesExenciones' => $porcentajesExenciones
        ]);
    }

    /**
     * @Route("/usuarios/nuevo", name = "newUser")
     * @Security("has_role('ROLE_DEPARTMENT')")
     */
    public function newUserAction(Request $request, \Swift_Mailer $mailer)
    {
        $usuario = new Usuario();
        $form = $this->createForm(NewUserType::class, $usuario, array('usuario' => $this->getUser()));
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            $validator = $this->get('validator');
            $errors = $validator->validate($usuario);

            $usuario->setNombre(mb_convert_encoding(mb_convert_case($usuario->getNombre(), MB_CASE_TITLE), "UTF-8"));
            $usuario->setApellidos(mb_convert_encoding(mb_convert_case($usuario->getApellidos(), MB_CASE_TITLE), "UTF-8"));
            if (count($errors) > 0) {
                $errorsString = $errors;
            }

            if ($form->isValid()) {

                if ('Departamento' === $this->getUser()->getRol()->getNombre()) {
                    $usuario->setDepartamento($this->getUser()->getDepartamento());
                }
                $usuario->setHash(base64_encode(random_bytes(20)));
                $usuario->setIsHashActive(true);
                $usuarios = $this->getDoctrine()->getRepository(Usuario::class)->encontrarPorPrioridad($usuario);
                if (count($usuarios) > 1) {
                    for ($k = 1; $k < count($usuarios); $k++) {
                        if ($usuarios[$k] == $usuario) {
                            $this->getDoctrine()->getRepository(Usuario::class)->guardarUsuario($usuario);
                        } else {
                            if ($usuario->getPrioridad() == $usuarios[$k]->getPrioridad()) {
                                $usuarios[$k]->setPrioridad($usuarios[$k]->getPrioridad() + 1);
                                $this->getDoctrine()->getRepository(Usuario::class)->guardarUsuario($usuarios[$k]);

                            }
                            if (count($usuarios) - 1 != $k) {
                                if ($usuarios[$k]->getPrioridad() != $usuarios[$k + 1]->getPrioridad()) {
                                    break;
                                }
                            }
                        }
                    }
                }
                $resultado = $this->getDoctrine()->getRepository(Usuario::class)->guardarUsuario($usuario);
                if (1 === $resultado) {
                    //------------------------------------------------------------------

                    $mailBody = $this->renderView('@App/Mails/newUser.html.twig', [
                        'host' => $_SERVER['SERVER_NAME'],
                        'user' => $usuario,
                        'hash' => urlencode($usuario->getHash())
                    ]);
                    $message = (new \Swift_Message('Bienvenido ' . $usuario->getNombre()))
                        ->setFrom($this->getParameter('mailer_user'))
                        ->setTo($usuario->getCorreo(), $usuario->getNombre())
                        ->setBody(
                            $mailBody,
                            'text/html'
                        );

                    $mailer->send($message);
                    //------------------------------------------------------------------

                    $this->get('session')->getFlashBag()->add(
                        'notice',
                        'user_added'
                    );
                } else {
                    $this->get('session')->getFlashBag()->add(
                        'notice',
                        'user_notadded'
                    );
                }

                return $this->redirectToRoute('listUsers');
            }else{
                $this->get('session')->getFlashBag()->add(
                    'notice',
                    'user_notadded'
                );
            }


        }
        return $this->render('AppBundle:users:register.html.twig', array(
            'form' => $form->createView()
        ));
    }

    /**
     * @Route("/usuarios/perfil/user={id}", name = "profileUser")
     * @Security("is_granted('ROLE_USER')")
     */
    public function profileAction(Request $request, Usuario $usuario)
    {
        $pass = new ChangePassword();
        $passForm = $this->createForm(ChangePasswordType::class, $pass);
        $passForm->handleRequest($request);
        $form = $this->createForm(EditUserType::class, $usuario, array('usuario' => $this->getUser()));
        $form->handleRequest($request);
        if ($form->isSubmitted()) {

            $usuario->setNombre(mb_strtolower($usuario->getNombre()));
            $usuario->setApellidos(mb_strtolower($usuario->getApellidos()));
            $usuario->setNombre(mb_convert_encoding(mb_convert_case($usuario->getNombre(), MB_CASE_TITLE), "UTF-8"));
            $usuario->setApellidos(mb_convert_encoding(mb_convert_case($usuario->getApellidos(), MB_CASE_TITLE), "UTF-8"));

            $validator = $this->get('validator');
            $errors = $validator->validate($usuario);
            if (count($errors) > 0) {
                $errorsString = $errors;
            }

            if ($form->isValid()) {
                $resultado = $this->getDoctrine()->getRepository(Usuario::class)->guardarUsuario($usuario);
                $usuarios = $this->getDoctrine()->getRepository(Usuario::class)->encontrarPorPrioridad($usuario);
                if (count($usuarios) > 1) {
                    for ($k = 1; $k < count($usuarios); $k++) {
                        if ($usuarios[$k] == $usuario) {
                            $this->getDoctrine()->getRepository(Usuario::class)->guardarUsuario($usuario);
                        } else {
                            if ($usuario->getPrioridad() == $usuarios[$k]->getPrioridad()) {
                                $usuarios[$k]->setPrioridad($usuarios[$k]->getPrioridad() + 1);
                                $this->getDoctrine()->getRepository(Usuario::class)->guardarUsuario($usuarios[$k]);

                            }
                            if (count($usuarios) - 1 != $k) {
                                if ($usuarios[$k]->getPrioridad() != $usuarios[$k + 1]->getPrioridad()) {
                                    break;
                                }
                            }
                        }
                    }
                }
                if (1 === $resultado) {
                    $this->get('session')->getFlashBag()->add(
                        'notice',
                        'user_edited'
                    );
                } else {
                    $this->get('session')->getFlashBag()->add(
                        'notice',
                        'user_notedited'
                    );
                }
                return $this->redirectToRoute('profileUser', array('id' => $usuario->getId()));
            }else{
                $this->get('session')->getFlashBag()->add(
                    'notice',
                    'user_notedited'
                );
            }
            return $this->redirectToRoute('profileUser', array('id' => $usuario->getId()));
        }
        if ($passForm->isSubmitted()) {

            $validator = $this->get('validator');
            $errors = $validator->validate($pass);
            if (count($errors) > 0) {
                foreach ($errors as $e){
                    if ($e->getMessage() === "Password should by at least 6 chars long"){
                        $this->get('session')->getFlashBag()->add(
                            'notice',
                            'user_pass_length'
                        );
                    }if ($e->getMessage() === "Wrong value for your current password"){
                        $this->get('session')->getFlashBag()->add(
                            'notice',
                            'user_pass_wrong'
                        );
                    }
                }

            }

            if ($passForm->isValid()) {
                $encoder = $this->container->get('security.password_encoder');
                $password = $encoder->encodePassword($usuario, $pass->getNewPassword());
                $usuario->setClave($password);
                $resultado = $this->getDoctrine()->getRepository(Usuario::class)->guardarUsuario($usuario);

                if (1 === $resultado) {
                    $this->get('session')->getFlashBag()->add(
                        'notice',

src/AppBundle/Resources/views/users/index.html.twig
{% extends '@App/template.html.twig' %}


{% block titulo %}

{% endblock %}

{% block body %}
    <section class="tabbable-line">
        <ul class="nav nav-tabs">
            <li class="active">
                <a href="{{ path('listUsers') }}"> Usuarios</a>
            </li>
            {% if is_granted('ROLE_DEPARTMENT') %}
                <li>
                    <a href="{{ path('newUser') }}">Nuevo Usuario</a>
                </li>
            {% endif %}
        </ul>
        <div class="portlet-body flip-scroll">
            <table class="table table-bordered table-striped table-condensed flip-content">
                <thead class="thead-dark flip-content">

                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Email</th>
                    <th scope="col">Departamento</th>
                    <th scope="col">Exenciones</th>
                    <th scope="col">Materias</th>
                    <th scope="col">Total</th>
                    <th scope="col">Acciones</th>

                </tr>
                </thead>
                <tbody>
                {% for u in usuarios %}
                    <tr>
                        <td>{{ u.prioridad }}</td>
                        <td>{{ u.nombre }} {{ u.apellidos }}</td>
                        <td>{{ u.correo }}</td>
                        <td>{{ u.departamento }}</td>
                        <td>{{ porcentajesExenciones[loop.index0] }}</td>
                        <td>{{ porcentajesMaterias[loop.index0] }}</td>
                        <td>{{ porcentajesMaterias[loop.index0] + porcentajesExenciones[loop.index0]}}</td>
                        <td>
                            <a class="btn btn-info btn-xs" href="{{ path('profileUser', {'id': u.id}) }}">
                                Ver Perfil
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
{% endblock %}
{% block stylesheets %}
    <style>
        section{
            margin: auto;
            margin-top: 2em;
            width: 80%;
        }
        @media
        only screen and (max-width: 992px){
            section{
                width: 100%;
            }
        }
    </style>
{% endblock %}

src/AppBundle/Resources/views/users/profile.html.twig
{% extends '@App/template.html.twig' %}


{% block titulo %}Perfil: {{ usuario }}{% endblock %}

{% block body %}
    <div class="tabbable-line">
        <ul class="nav nav-tabs">
            <li class="active">
                <a href="#tab_1_1" data-toggle="tab"> Información </a>
            </li>
            <li>
                <a href="#tab_1_3" data-toggle="tab">Materias</a>
            </li>
            <li>
                <a href="#tab_1_4" data-toggle="tab">Exención</a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane fade active in" id="tab_1_1">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group form-md-line-input">
                            <span>Nombre:</span>
                            <span class="form-control">{{ usuario.nombre }}</span>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group form-md-line-input">
                            <span>Apellidos: </span>
                            <span class="form-control">{{ usuario.apellidos }}</span>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group form-md-line-input">
                            <span>Email:</span>
                            <span class="form-control">{{ usuario.correo }}</span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group form-md-line-input">
                            <span>Departamento:</span>
                            <span class="form-control">{{ usuario.departamento }}</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="tab_1_3">
                <div class="row">
                    <div class="portlet-body flip-scroll">
                        <table class="table table-bordered table-striped table-condensed flip-content">
                            <thead class="thead-dark flip-content">
                        <tr>
                            <th scope="col">Código</th>
                            <th scope="col">Curso</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Horas Semanales</th>
                            <th scope="col">Horas Totales</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for m in usuario.UsuarioMateria %}
                            <tr>
                                <td>{{ m.materia.codigo }}</td>
                                <td>{{ m.materia.curso }}</td>
                                <td>{{ m.materia.nombre }}</td>
                                <td>{{ m.materia.horasSemanales }}</td>
                                <td>{{ m.materia.horasTotales }}</td>
                                <td>
                                    <a class="btn btn-info" href="#">Mas Info</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="tab_1_4">
                <div class="row">
                    <div class="portlet-body flip-scroll">
                        <table class="table table-bordered table-striped table-condensed flip-content">
                            <thead class="thead-dark flip-content">
                        <tr>
                            <th scope="col">Código</th>
                            <th scope="col">Nombre</th>
                            <th scope="col">Horas Semanales</th>
                            <th scope="col">Horas Totales</th>
                            <th scope="col">Acciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for m in usuario.exencion %}
                            <tr>
                                <td>{{ m.codigo }}</td>
                                <td>{{ m.nombre }}</td>
                                <td>{{ m.horasSemanales }}</td>
                                <td>{{ m.horasTotales }}</td>
                                <td>
                                    <a class="btn btn-info btn-xs" href="{{ path('profileExencion', {'id': m.id}) }}">
                                        Mas Info
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block javascripts %}

{% endblock %}
{% block stylesheets %}
    <style>
        .del{
            text-decoration: none;
            color: #D91E18;
        }
        .del:hover{
            color: #D91E18;
        }
    </style>
{% endblock %}

src/AppBundle/Resources/views/users/register.html.twig
{% extends '@App/template.html.twig' %}


{% block titulo %}{% endblock %}

{% block body %}
    <section class="tabbable-line">
        <ul class="nav nav-tabs">
            <li>
                <a href="{{ path('listUsers') }}"> Usuarios</a>
            </li>
            <li class="active">
                <a href="{{ path('newUser') }}">Nuevo Usuario</a>
            </li>
        </ul>
        <div class="row">
            <div class="col-md-12">
                {{ form_start(form) }}
                <div style="display: none;">
                    {{ form_errors(form.correo) }}
                    {{ form_errors(form.nombre) }}
                    {{ form_errors(form.apellidos) }}
                    {{ form_errors(form.rol) }}
                    {{ form_errors(form.prioridad) }}
                    {% if app.user.rol.nombre == 'Admin' %}
                        {{ form_errors(form.departamento) }}
                    {% endif %}
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group form-md-line-input">
                            {{ form_label(form.correo) }}
                            {{ form_widget(form.correo) }}
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group form-md-line-input">
                            {{ form_label(form.nombre) }}
                            {{ form_widget(form.nombre) }}
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group form-md-line-input">
                            {{ form_label(form.apellidos) }}
                            {{ form_widget(form.apellidos) }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    {% if app.user.rol.nombre == 'Admin' %}
                        <div class="col-md-4">
                            <div class="form-group form-md-line-input">
                                {{ form_label(form.departamento) }}
                                {{ form_widget(form.departamento) }}
                            </div>
                        </div>
                    {% endif %}
                    <div class="col-md-4">
                        <div class="form-group form-md-line-input">
                            {{ form_label(form.rol) }}
                            {{ form_widget(form.rol) }}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group form-md-line-input">
                            {{ form_label(form.prioridad) }}
                            {{ form_widget(form.prioridad) }}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <input type="submit" class="btn btn-success">
                    </div>
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </section>
{% endblock %}

{% block stylesheets %}
    <style>
        main{
            width: 30%;
            margin: auto;
            margin-top: 2em;
        }
        .row{
            padding: 0.25em;
        }
    </style>
{% endblock %}