src/AppBundle/Entity/Materia.php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Materia
 *
 * @ORM\Table(name="materia")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\MateriaRepository")
 */
class Materia
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(name="Nombre", type="string", length=50)
     * @Assert\Length(max="50")
     */
    private $nombre;

    /**
     * @var string
     * @ORM\Column(name="Code", type="string", length=9)
     * @Assert\Length(max="9")
     */
    private $codigo;

    /**
     * @var int
     * @Assert\GreaterThan(value="0")
     * @Assert\Type(type="int")
     * @ORM\Column(name="HorasSemanales", type="integer")
     */
    private $horasSemanales;

    /**
     * @var int
     * @Assert\GreaterThan(value="0")
     * @Assert\Type(type="int")
     * @ORM\Column(name="HorasTotales", type="integer")
     */
    private $horasTotales;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Departamento", inversedBy="materia", fetch="EXTRA_LAZY")
     */
    private $departamento;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Usuario_Materia", mappedBy="materia", fetch="EXTRA_LAZY")
     * @var Usuario_Materia
     */
    private $usuario_materia;

    /**
     * @var string
     * @ORM\Column(name="Curso", type="string", length=12)
     * @Assert\Length(max="12")
     */
    private $curso;

    /**
     * Materia constructor.
     */
    public function __construct()
    {
        $this->usuario_materia = new ArrayCollection();
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return $this->getNombre();
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     * @return Materia
     */
    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return string
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * @param string $nombre
     * @return Materia
     */
    public function setNombre($nombre)
    {
        $this->nombre = ucfirst($nombre);
        return $this;
    }

    /**
     * @return string
     */
    public function getCodigo()
    {
        return $this->codigo;
    }

    /**
     * @param string $codigo
     * @return Materia
     */
    public function setCodigo($codigo)
    {
        $this->codigo = $codigo;
        return $this;
    }

    /**
     * @return int
     */
    public function getHorasSemanales()
    {
        return $this->horasSemanales;
    }

    /**
     * @param int $horasSemanales
     * @return Materia
     */
    public function setHorasSemanales($horasSemanales)
    {
        $this->horasSemanales = $horasSemanales;
        return $this;
    }

    /**
     * @return int
     */
    public function getHorasTotales()
    {
        return $this->horasTotales;
    }

    /**
     * @param int $horasTotales
     * @return Materia
     */
    public function setHorasTotales($horasTotales)
    {
        $this->horasTotales = $horasTotales;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getDepartamento()
    {
        return $this->departamento;
    }

    /**
     * @param mixed $departamento
     * @return Materia
     */
    public function setDepartamento($departamento)
    {
        $this->departamento = $departamento;
        return $this;
    }

    /**
     * @return Usuario_Materia
     */
    public function getUsuarioMateria()
    {
        return $this->usuario_materia;
    }

    /**
     * @param Usuario_Materia $usuario_Materia
     * @return $this
     */
    public function addUsuarioMateria(Usuario_Materia $usuario_Materia)
    {
        if (!$this->usuario_materia->contains($usuario_Materia)) {
            $this->usuario_materia[] = $usuario_Materia;
            $usuario_Materia->setMateria($this);
        }
        return $this;
    }

    /**
     * @param Usuario_Materia $usuario_Materia
     * @return $this
     */
    public function removeUsuarioMateria(Usuario_Materia $usuario_Materia)
    {
        if ($this->usuario_materia->contains($usuario_Materia)) {
            $this->usuario_materia->removeElement($usuario_Materia);
            $usuario_Materia->setMateria(null);
        }
        return $this;
    }

    /**
     * @return string
     */
    public function getCurso()
    {
        return $this->curso;
    }

    /**
     * @param string $curso
     * @return Materia
     */
    public function setCurso($curso)
    {
        $this->curso = $curso;
        return $this;
    }

}

src/AppBundle/Controller/DefaultController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Configuracion;
use AppBundle\Entity\Exencion;
use AppBundle\Entity\Materia;
use AppBundle\Entity\Usuario;
use AppBundle\Entity\Usuario_Materia;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class DefaultController extends Controller
{
    /**
     * @Route("/", name = "homepage")
     * @Security("has_role('ROLE_USER')")
     */
    public function indexAction(Request $request)
    {

        return $this->render('@App/default/index.html.twig', [
        ]);
    }

    /**
     * @Route("/seleccion", name = "seleccion")
     * @Security("has_role('ROLE_USER')")
     */
    public function selectAction()
    {
        $config = $this->getDoctrine()->getRepository(Configuracion::class)->encontrarConfiguracion();
        $exenciones = $this->getDoctrine()->getRepository(Exencion::class)->encontrarExencionesRestantes($this->getUser());
        $materias = $this->getDoctrine()->getRepository(Materia::class)->encontrarMateriasRestantes($this->getUser());
        $usuario_materia = $this->getDoctrine()->getRepository(Usuario_Materia::class)->encontrarPorCursoYDepartamento($this->getUser(), $config);
        $m = $this->getDoctrine()->getRepository(Usuario::class)->getPorcentajeMateriasAsignadas($this->getUser());
        $e = $this->getDoctrine()->getRepository(Usuario::class)->getPorcentajeExencionesAsignadas($this->getUser());

        $m = ($m /$config->getHorasMin()) * 100;
        $e = ($e /$config->getHorasMin()) * 100;

        $m = round($m, 2);
        $e = round($e, 2);

        return $this->render('@App/default/seleccion.html.twig', [
            'exenciones' => $exenciones,
            'materias' => $materias,
            'usuario_materia' => $usuario_materia,
            'm' => $m,
            'e' => $e,
            'config' => $config
        ]);
    }
}

src/AppBundle/Resources/views/default/index.html.twig
{% extends '@App/template.html.twig' %}
{% block titulo %}{% endblock %}
{% block body %}
{% endblock %}

{% block stylesheets %}
{% endblock %}

src/AppBundle/Resources/views/default/seleccion.html.twig
{% extends '@App/template.html.twig' %}
{% block titulo %}{% endblock %}
{% block body %}
    <div>
        <h2>Porcentaje de horas seleccionadas. {{ e + m }}%</h2>
        <small>Porcentaje calculado respecto a horas minimas en la configuración.</small>
        <span style="display: flex; flex-wrap: nowrap">
            <span style="flex: 1 1 50%">Horas Minimas: {{ config.horasMin }}</span>
            <span style="flex: 1 1 50%">Horas Maximas: {{ config.horasMax }}</span>
        </span>
        <div class="progress">
           {% if (e + m) >= 100 %}
             {% if e > m %}
                 <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: {{ 100 - m }}%;">
                     Exenciones ({{ e }}%)
                 </div>
                 <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: {{ m }}%;">
                     Materias ({{ m }}%)
                 </div>
                 {% elseif m >e %}
                     <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: {{ e }}%;">
                         Exenciones ({{ e }}%)
                     </div>
                     <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: {{ 100 - e }}%;">
                         Materias ({{ m }}%)
                     </div>
                 {% else %}
                 <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 50%;">
                     Exenciones ({{ e }}%)
                 </div>
                 <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 50%;">
                     Materias ({{ m }}%)
                 </div>
             {% endif %}
               {% else %}
                   <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: {{ e }}%;">
                       Exenciones ({{ e }}%)
                   </div>
                   <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: {{ m }}%;">
                       Materias ({{ m }}%)
                   </div>
           {% endif %}
        </div>
    </div>
    <div class="asignados">
        <div class="exenciones">
            <h4>Exenciones</h4>
            {% if app.user.exencion.count >0 %}
                <div class="portlet-body flip-scroll">
                    <table class="table table-bordered table-striped table-condensed flip-content">
                        <thead class="thead-dark flip-content">
                    <tr>
                        <th scope="col">Nombre</th>
                        <th scope="col">Horas Semanales</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for m in app.user.exencion %}
                        <tr>
                            <td>{{ m.nombre }}</td>
                            <td>{{ m.horasSemanales }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                </div>
            {% else %}
                No dispone de ninguna exencion asignada
            {% endif %}
        </div>
        <div class="materias">
            <h4>Materias</h4>
            {% if app.user.usuarioMateria.count >0 %}
                <div class="portlet-body flip-scroll">
                    <table class="table table-bordered table-striped table-condensed flip-content">
                        <thead class="thead-dark flip-content">
                    <tr>
                        <th scope="col">Prioridad</th>
                        <th scope="col">Curso</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Horas Semanales</th>
                        <th scope="col">Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for m in app.user.usuarioMateria %}
                        <tr>
                            <td>{{ m.turno }}</td>
                            <td>{{ m.materia.curso }}</td>
                            <td>{{ m.materia.nombre }}</td>
                            <td>{{ m.materia.horasSemanales }}</td>
                            <td>
                                <a href="{{ path('prioridadUsuario_materia', {'materia': m.materia.id, 'usuario': app.user.id}) }}">
                                    Cambiar
                                </a>
                            </td>
                        </tr>

                    {% endfor %}
                    </tbody>
                </table>
                </div>
            {% else %}
                No dispone de ninguna materia asignada
            {% endif %}
        </div>
    </div>
    <hr>
    <div class="portlet-body">
        <div class="panel-group accordion" id="accordion">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a class="accordion-toggle accordion-toggle-styled" data-toggle="collapse"
                           data-parent="#accordion" href="#dp_1">
                            Exenciones ({{ exenciones.count }})
                        </a>
                    </h4>
                </div>
                <div id="dp_1" class="panel-collapse collapse">
                    <div class="portlet-body flip-scroll">
                        <table class="table table-bordered table-striped table-condensed flip-content">
                            <thead class="thead-dark flip-content">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Nombre</th>
                                <th scope="col">Horas Semanales</th>
                            </tr>
                            </thead>
                            <tbody>
                                {% for e in exenciones %}

                                    <tr>
                                        <td>
                                            <a class="btn btn-info btn-xs"
                                               href="{{ path('selectExencion', {'exencion': e.id , 'usuario': app.user.id}) }}">
                                                Seleccionar
                                            </a>
                                        </td>
                                        <td>
                                            {{ e }}
                                        </td>
                                        <td>
                                            {{ e.horasSemanales }}
                                        </td>
                                    </tr>
                                {% else %}
                                    <tr>
                                        <td colspan="3">No hay ninguna exención que pueda seleccionar</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a class="accordion-toggle accordion-toggle-styled" data-toggle="collapse"
                           data-parent="#accordion" href="#dp_2">
                            Materias - Sin Asignar ({{ materias.count }})
                        </a>
                    </h4>
                </div>
                <div id="dp_2" class="panel-collapse collapse">
                    <div class="portlet-body flip-scroll">
                        <table class="table table-bordered table-striped table-condensed flip-content">
                            <thead class="thead-dark flip-content">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Curso</th>
                                <th scope="col">Código</th>
                                <th scope="col">Nombre</th>
                                <th scope="col">Horas Semanales</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for m in materias %}
                                <tr>
                                    <td>
                                        <a class="btn btn-info btn-xs"
                                           href="{{ path('selectMateria', {'materia': m.id , 'usuario': app.user.id}) }}">
                                            Seleccionar
                                        </a>
                                    </td>
                                    <td>
                                        {{ m.curso }}
                                    </td>
                                    <td>
                                        {{ m.codigo }}
                                    </td>
                                    <td>
                                        {{ m }}
                                    </td>
                                    <td>
                                        {{ m.horasSemanales }}
                                    </td>
                                </tr>
                            {% else %}
                                <tr>
                                    <td colspan="3">No hay ninguna materia que pueda seleccionar</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a class="accordion-toggle accordion-toggle-styled" data-toggle="collapse"
                           data-parent="#accordion" href="#dp_3">
                            Materias - Asignadas ({{ usuario_materia.count }})
                        </a>
                    </h4>
                </div>
                <div id="dp_3" class="panel-collapse collapse">
                    <div class="portlet-body flip-scroll">
                        <table class="table table-bordered table-striped table-condensed flip-content">
                            <thead class="thead-dark flip-content">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Nombre</th>
                                <th scope="col">Horas Semanales</th>
                                <th scope="col">Usuario</th>
                                <th scope="col">Prioridad</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for m in usuario_materia %}
                                <tr>
                                    <td>
                                        <a class="btn btn-info btn-xs"
                                           href="{{ path('selectUsuario_Materia',{'materia': m.materia.id, 'usuario': m.usuario.id}) }}">
                                            Seleccionar
                                        </a>
                                    </td>
                                    <td>
                                        {{ m.materia }}
                                    </td>
                                    <td>
                                        {{ m.materia.horasSemanales }}
                                    </td>
                                    <td>
                                        {{ m.usuario }}
                                    </td>
                                    <td>
                                        {{ m.turno }}
                                    </td>
                                </tr>
                            {% else %}
                                <tr>
                                    <td colspan="4">
                                        No puede seleccionar ninguna materia de otros usuarios
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block stylesheets %}
    <style>
        .asignados {

            display: flex;
            flex-wrap: wrap;
        }

        .materias {
            text-align: center;
            box-sizing: border-box;
            padding: 1em;
            flex: 1 1 50%;
        }

        .exenciones {
            text-align: center;
            box-sizing: border-box;
            padding: 1em;
            flex: 1 1 50%;
        }
    </style>
{% endblock %}